# Site settings
title: Taylor Whitman Poulos
email: poulos.taylor.w@gmail.com
description: "Designer and writer studying at Carnegie Mellon University Portfolio and selected writing."
baseurl: ""
url: "http://twp.io"

# Build settings
markdown: kramdown
permalink: pretty
